hydra: 
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}
  
# Logging Settings
log_dir: /home/odonca/workspace/rpad/data/equivariant_pose_graph/logs
experiment: pretraining
wandb_group: mug_test
image_logging_period: 1000

# Dataset Settings
dataset_root: /home/odonca/workspace/rpad/taxpose/third_party/ndf_robot/data/training_data
pretraining_data_path: /home/odonca/workspace/rpad/taxpose/third_party/ndf_robot/data
num_workers: 16
batch_size: 8
num_points: 1024
dataset_index: None
cloud_class: 0
cloud_type: init
overfit: false
seed: 0

# Network Settings
emb_dims: 512
emb_nn: dgcnn
input_dims: 3
conditioning_size: 0

inital_sampling_ratio: 1

# Loss Settings
normalize_features: true
con_weighting: dist
l2_reg_weight: 0
temperature: 0.1

# Training Settings
checkpoint_file: Null
lr: 1e-4